version: "3"

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false # Exclude all containers (they will be enabled with label "traefik.enable=true")

      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"

  whoami: # LUI C'EST TON FRONT PAR EXEMPLE accessible sur ton ip server/titi   
    image: traefik/whoami # A container that exposes an API to show its IP address
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.whoami.rule=Path(`/juju`)

  whoami2: # LUI C'EST TON BACK PAR EXEMPLE  accessible sur ton ip server/toto
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.whoami2.rule=Path(`/toto`)
